version: '3.8'

services:
  postgres:
    image: postgres:latest
    container_name: lunchgowhere_postgres
    environment:
      POSTGRES_DB: postgres
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: password
    networks:
      - my_network

  redis:
    image: redis:latest
    container_name: lunchgowhere_redis
    networks:
      - my_network

  nginx:
    image: nginx:latest
    container_name: lunchgowhere_nginx
    ports:
      - "9090:9090"
    volumes:
      - ./nginx.conf:/etc/nginx/nginx.conf
    networks:
      - my_network
    depends_on:
      - lunchgowhere-fe

  lunchgowhere:
    build: ./lunchgowhere
    container_name: lunchgowhere
    networks:
      - my_network
    depends_on:
      - redis
      - postgres

  lunchgowhere-fe:
    build: ./lunchgowhere-fe
    container_name: lunchgowhere-fe
    networks:
      - my_network
    depends_on:
      - lunchgowhere

networks:
  my_network:
    driver: bridge