version: '3.8'

services:
  postgres:
    image: postgres:latest
    container_name: my_postgres_container_1
    ports:
      - "5432:5432"
    environment:
      POSTGRES_DB: postgres
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: password

  redis:
    image: redis:latest
    container_name: my_redis_container
    ports:
      - "6379:6379"

  nginx:
    image: nginx:latest
    container_name: my_nginx_proxy
    ports:
      - "9090:9090"
    volumes:
      - ./nginx.conf:/etc/nginx/nginx.conf
